Update graphqler.py
Fix a bug which did NOT parser JSON when load introspection.json


(venv) labs :: graphql/graphqler » python graphqler.py -f ~/Desktop/response.json -u "http://3.x.x.132:4000/graphql"  -m all_args
Traceback (most recent call last):
  File "/Users/x/graphql/graphqler/graphqler.py", line 666, in <module>
    main()
  File "/Users/x/graphql/graphqler/graphqler.py", line 617, in main
    query_type_name,mutation_type_name = get_query_and_mutation_types(schema)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/x/graphql/graphqler/graphqler.py", line 305, in get_query_and_mutation_types
    if schema['data']['__schema']['queryType'] is not None:
       ~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'